import requests
import os
import mysql.connector
from datetime import datetime

def generate_blog(api_key, prompt):
    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    # Initial message for blog title
    
    user_message = {"role": "user", "content": prompt}
    initial_message = {"role": "system", "content": "כתוב תוכן בפורמט DIV,H1,H2,H3,H4,H5,STRONG,SPAN,BR,P,TD,  עם תגיות לפסקאות, רשימות והדגשות  בצורה מסודרת ויפה שתקדם את העסק שלי בצורה יפה  כתוב מעל 1000 מילים תוך כדי שימוש בתכונות SEO עבור נושאי ${prompt}."}
    # Messages for additional content if available
    meassage1=input("m1")
    meassage2=input("m2")
    meassage3=input("m3")
    meassage4=input("m4")
    additional_messages = [
        {"role": "user", "content": meassage1},
        {"role": "user", "content": meassage2},
        {"role": "user", "content": meassage3},
        {"role": "user", "content": meassage4},

    ]

    data_list = [
        {"model": "gpt-3.5-turbo", "messages": [initial_message, user_message]},
        {"model": "gpt-3.5-turbo", "messages": [initial_message, additional_messages[0]]},
        {"model": "gpt-3.5-turbo", "messages": [initial_message, additional_messages[1]]},
        {"model": "gpt-3.5-turbo", "messages": [initial_message, additional_messages[2]]},
        {"model": "gpt-3.5-turbo", "messages": [initial_message, additional_messages[3]]},

    ]

    blog_content = ""

    for data in data_list:
        response = requests.post(url, headers=headers, json=data)
        response_data = response.json()

        if 'choices' in response_data and response_data['choices']:
            content = response_data['choices'][0]['message']['content'].strip()
            blog_content += content + "\n\n"

    if blog_content:
        return blog_content
    else:
        return "Error: No content generated by the API."


def save_to_html(html_content, file_path):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(html_content)

def save_to_db(blog_content, prompt, db_config, html_file_path):
    db_connection = mysql.connector.connect(
        host=db_config['host'],
        user=db_config['user'],
        password=db_config['password'],
        database=db_config['database']
    )
    cursor = db_connection.cursor()
    new_entry = (
        "מנהל האתר",
        datetime.now().strftime("%Y-%m-%d"),
        datetime.now().strftime("%H:%M:%S"),
        prompt,
        blog_content,
        html_file_path
    )
    query = """
    INSERT INTO blogs (author, date, time, description, content, link)
    VALUES (%s, %s, %s, %s, %s, %s)
    """
    cursor.execute(query, new_entry)
    db_connection.commit()
    cursor.close()
    db_connection.close()

def main():
    api_key = "yourApicode"  # Replace with your actual API key
    prompt = input("What is the topic of the blog? ")

    blog_content = generate_blog(api_key, prompt)

    html_folder_path = "C:\\Users\\alont\\AppData\\Roaming\\Code\\User\\globalStorage\\humy2833.ftp-simple\\remote-workspace-temp\\ca1dc6f665ccd3a103bcda285eee5af6\\public_html"
    os.makedirs(html_folder_path, exist_ok=True)
    html_link=f"blog_{datetime.now().strftime('%Y%m%d%H%M%S')}.html"
    html_file_path = os.path.join(html_folder_path,html_link)

    html_content = f"""<!DOCTYPE html>
<html lang="heb" dir="rtl">
  <head>
    <!--- Basic Page Needs  -->
    <meta charset="utf-8" />
    <title>WebsiteIL {prompt}</title>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="keywords" content="" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta charset="UTF-8">
<meta name="robots" content="index, follow">
    <!-- Mobile Specific Meta  -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />

    <!-- Google Fonts -->

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
      rel="stylesheet"
    />

    <!-- CSS -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
    <!-- Jquery ui CSS -->
    <link rel="stylesheet" href="assets/css/jquery-ui.css" />
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="assets/css/font-awesome.min.css" />
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="assets/css/owl.theme.default.min.css" />
    <link rel="stylesheet" href="/stylecss.css" />

    <!-- Animate CSS -->
    <link rel="stylesheet" href="assets/css/animate.css" />
    <!-- Main StyleSheet CSS -->
    <link rel="stylesheet" href="assets/css/style.css" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="assets/css/responsive.css" />

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="/Screenshot 2024-04-27 184734.png"
    />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id="preloader"></div>
 <div id="contactSidebar" class="contact-sidebar">
      <button id="closeButton" class="close-button">&times;</button>
      <h4>שלח לנו הודעה</h4>
      <form id="contactForm" class="cf-sidebar">
        <div class="form-group">
          <input type="text" name="name" placeholder="שם מלא" required />
        </div>
        <div class="form-group">
          <input
            type="email"
            name="email"
            placeholder="כתובת אימייל"
            required
          />
        </div>
        <div class="form-group">
          <input type="text" name="phone" placeholder="מספר טלפון" />
        </div>
        <div class="form-group">
          <textarea
            name="message"
            placeholder="כתוב את ההודעה שלך כאן"
            required
          ></textarea>
        </div>
        <button type="submit" class="btn-b btn-style_5">שלח עכשיו</button>
      </form>
    </div>
    <!-- Header Area -->
    <header class="header-area header_3">
      <nav class="navbar navbar-expand-lg Saased-nav">
        <div class="container">
          <a class="navbar-brand" href="#"
            ><img src="/websiteil.png" style="height: 100px" class="logo"
          /></a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/index.html"
                  >דף הבית</a
                >
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  הבלוג שלנו
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <!-- פריטים דינמיים יוכנסו כאן -->
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- /Header Area -->

    <!-- Innerpage Title Area -->
    <section class="innerpage-title-area">
      <div class="container">
        <div class="row">
          <div class="col-md-10">
            <div class="section-title innerSection-title">
              <h3>ברוכים הבאים לבלוג שלנו </h3>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- /Innerpage Title Area -->
    <!-- Blog Area -->
    <section class="innerpage-section blogpage-content section-padding">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="inner-section-content bpc-inner">
              <div class="blogitem">
                <div class="blogitem-img">
                </div>
                <div class="blogitem-text-content">
                  <div class="sbp-V2-meta">
                    <ul>
                      <li>פורסם ב{datetime.now().strftime("%Y-%m-%d")}:</li>
                      <li>פרסום בגוגל</li>
                    </ul>
                  </div>
                  <div class="sbp-V2-text">
                          <div class="sbp-V2-text">
          {blog_content}
          <!-- Google Calendar Appointment Scheduling begin -->
<iframe src="https://calendar.google.com/calendar/appointments/schedules/AcZssZ0nAri-M7SR965ZmQhxX9kHtg5a29KIgesiqEsixkuVMIgaYFxa3ALswCMn4-t4piy-axjPtJyg?gv=true" style="border: 0" width="100%" height="600" frameborder="0"></iframe>
<!-- end Google Calendar Appointment Scheduling -->
          <h1>מעוניינים ב-{prompt}?</h1>
<h3>התקשרו אלינו עכשיו או כתבו לנו ! </h3>
<h3>0544871731</h3>
                      </div>

                  </div>
                </div>
                <div class="blogitem-tags">
                  <div class="blogitem-tags-title">
                  </div>
                          <h1>{prompt}</h1>
<form class="cf3" id="contactForm">
                <h4>שלח לנו הודעה</h4>
                <div class="form-group">
                  <input
                    type="text"
                    class="cf3-input"
                    name="name"
                    placeholder="שם מלא"
                  />
                </div>
                <div class="form-group">
                  <input
                    type="email"
                    class="cf3-input"
                    name="email"
                    placeholder="כתובת אימייל"
                  />
                </div>
                <div class="form-group">
                  <input
                    type="text"
                    class="cf3-input"
                    name="phone"
                    placeholder="מספר טלפון"
                  />
                </div>
                <div class="form-group">
                  <textarea
                    name="message"
                    id="msag"
                    placeholder="כתוב את ההודעה שלך כאן"
                  ></textarea>
                </div>
                <button type="submit" class="btn-b btn-style_5">
                  שלח עכשיו
                </button>
              </form>
                  <ul>
                    <li><a href="#">קידום אורגני</a></li>
                    <li><a href="#">פיתוח אתרים</a></li>
                    <li><a href="#">קידום SEO</a></li>
                    <li><a href="#">קידום ממומן</a></li>
                    <li><a href="#">פרסום בגוגל </a></li>
                  </ul>
                </div>

       <div class="blogitem-commentbox mt-50">
    <div id="commentsContainer">
        <!-- כאן יוצגו התגובות -->
    </div>
    <h5 class="small-title">השאר תגובה</h5>
    <form class="tm-commentbox" id="commentForm" method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="tm-commentbox-singlefield">
                    <input type="text" name="comment_name" class="form-control" placeholder="שם" />
                </div>
                <div class="tm-commentbox-singlefield">
                    <input type="email" name="comment_email" class="form-control" placeholder="אימייל" />
                </div>
                <div class="tm-commentbox-singlefield">
                    <input type="text" name="comment_website" class="form-control" placeholder="כתובת אתר (אם יש)" />
                </div>
            </div>
            <div class="col-md-8">
                <div class="tm-commentbox-singlefield">
                    <textarea name="comment_content" class="form-control" placeholder="כתוב את התוכן שלך כאן"></textarea>
                </div>
                <div class="tm-commentbox-singlefield bdc-btn-box">
                    <button type="submit" id="submitComment" class="tm-button">הגב</button>
                </div>
            </div>
        </div>
    </form>
</div>

                <!--// Blogitem Commentbox -->
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="sidebar-wrapper">
              <aside
                class="widget-area"
                role="complementary"
                aria-label="Blog Sidebar"
              >
                <section class="widget widget_search">
                  <form role="search" method="get" class="search-form">
                    <input
                      type="search"
                      id="strickSearch"
                      class="search-field"
                      placeholder="Search …"
                      value=""
                      name="s"
                    />
                    <button type="submit" class="search-submit">
                      <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                  </form>
                </section>
      
        <section class="widget recent_post_entries">

                <h2 class="widget-title">Recent Posts</h2>
                    <div id="recentPostsContainer"></div>

               </section>
                

                <section class="widget widget_tag_cloud">
                  <h2 class="widget-title">Post Tags</h2>
                  <div class="tagcloud">
                    <ul class="wp-tag-cloud">
                      <li><a href="#" class="tag-cloud-link">קידום אתרים</a></li>
                      <li><a href="#" class="tag-cloud-link">פיתוח אתרים</a></li>
                      <li><a href="#" class="tag-cloud-link">קידום ב2024</a></li>
                      <li><a href="#" class="tag-cloud-link">למה לקדם בגוגל?</a></li>
                      <li><a href="#" class="tag-cloud-link">מהו קידום?</a></li>
                      <li>
                        <a href="#" class="tag-cloud-link">Illustration</a>
                      </li>
                      <li><a href="#" class="tag-cloud-link">מהירות אתר בנייד</a></li>
                      <li><a href="#" class="tag-cloud-link">הגיע הזמן לאתר חדש</a></li>
                    </ul>
                  </div>
                </section>
              
              </aside>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- /Blog Area -->
    
 

      <!-- Footer Area -->
    <footer class="footer-area footer3">
      <div class="footer-widget-area">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="f-widget f-logo-text">
                <img src="/websiteil.png" alt="" />
                <p>
                 WebsiteIL
                 האתר הכי ישראלי ליצירת אתר אינטרנט 
                </p>
                <p>
                אמינות , יצירתיות , מסירות ואהבה למקצוע 
                </p>
              </div>
            </div>
            <div class="col-md-5">
              <div class="row">
                <div class="col-md-6">
                  <div class="f-widget">
                    <h4>לינקים שימושיים</h4>
                    <ul class="fw-list">
                      <li><a href="#">מידניות הפרטיות</a></li>
                    </ul>
                  </div>
                </div>
                 <div class="col-md-6">
                  <div class="f-widget">
                    <h4>הבלוג שלנו</h4>
    <ul class="fw-list" id="blogList">
                    </ul>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="f-widget">
                    <h4>המוצרים שלנו:</h4>
                    <ul class="fw-list">
                      <li><a href="#">קידום אתרים</a></li>
                      <li><a href="#">SEO</a></li>
                      <li><a href="#">פיתוח אתרים בשופיפיי</a></li>
                      <li><a href="#">קידום בפייסבוק</a></li>
                      <li><a href="#">פיתוח אתרים בJava_Script</a></li>
                      <li><a href="#">WIX WIX WIX</a></li>
                      <li><a href="#">דף נחיתה</a></li>
                      <li><a href="#">פרסום בגוגל​
</a></li>
                      <li><a href="#">בניית אתרים לעסקים קטנים ובינוניים
</a></li>
                      <li><a href="#">בניית חנות אינטרנטית</a></li>
                      <li><a href="#">
פיתוח אתרים</a></li>

                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-3">
              <div class="f-widget">
                <div class="newsletter-form">
                  <h4>Subscribe Now</h4>
                  <form class="form-inline">
                    <input
                      type="text"
                      class="form-control"
                      name="nl-email"
                      placeholder="אימייל לעדכונים "
                    />
                    <button type="submit" class="btn btn-default">
                      <i class="fa fa-paper-plane" aria-hidden="true"></i>
                    </button>
                  </form>
                </div>
              </div>
              <div class="f-widget fw-social">
                <h4>שמור על קשר</h4>
                <ul class="fws-list">
                  <li>
                    <a href="#"
                      ><i class="fa fa-facebook-square" aria-hidden="true"></i
                    ></a>
                  </li>
                  <li>
                    <a href="#"
                      ><i class="fa fa-twitter-square" aria-hidden="true"></i
                    ></a>
                  </li>
                  <li>
                    <a href="#"
                      ><i class="fa fa-linkedin-square" aria-hidden="true"></i
                    ></a>
                  </li>
                  <li>
                    <a href="#"
                      ><i
                        class="fa fa-google-plus-square"
                        aria-hidden="true"
                      ></i
                    ></a>
                  </li>
                  <li>
                    <a href="#"
                      ><i class="fa fa-pinterest-square" aria-hidden="true"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-copyright-area">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="fc-text">
                <p>© כל הזכויות שמורות ל-WebsiteIL</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- /Footer Area -->

<input class="chat-menu hidden" id="offchat-menu" type="checkbox" />
<div class="sticky-button" id="sticky-button">
  <label for="offchat-menu">
    <svg class="chat-icon" viewBox="0 0 24 24">
      <path d="M12.04 2C6.58 2 2.13 6.45 2.13 11.91C2.13 13.66 2.59 15.36 3.45 16.86L2.05 22L7.3 20.62C8.75 21.41 10.38 21.83 12.04 21.83C17.5 21.83 21.95 17.38 21.95 11.92C21.95 9.27 20.92 6.78 19.05 4.91C17.18 3.03 14.69 2 12.04 2M12.05 3.67C14.25 3.67 16.31 4.53 17.87 6.09C19.42 7.65 20.28 9.72 20.28 11.92C20.28 16.46 16.58 20.15 12.04 20.15C10.56 20.15 9.11 19.76 7.85 19L7.55 18.83L4.43 19.65L5.26 16.61L5.06 16.29C4.24 15 3.8 13.47 3.8 11.91C3.81 7.37 7.5 3.67 12.05 3.67M8.53 7.33C8.37 7.33 8.1 7.39 7.87 7.64C7.65 7.89 7 8.5 7 9.71C7 10.93 7.89 12.1 8 12.27C8.14 12.44 9.76 14.94 12.25 16C12.84 16.27 13.3 16.42 13.66 16.53C14.25 16.72 14.79 16.69 15.22 16.63C15.7 16.56 16.68 16.03 16.89 15.45C17.1 14.87 17.1 14.38 17.04 14.27C16.97 14.17 16.81 14.11 16.56 14C16.31 13.86 15.09 13.26 14.87 13.18C14.64 13.1 14.5 13.06 14.31 13.3C14.15 13.55 13.67 14.11 13.53 14.27C13.38 14.44 13.24 14.46 13 14.34C12.74 14.21 11.94 13.95 11 13.11C10.26 12.45 9.77 11.64 9.62 11.39C9.5 11.15 9.61 11 9.73 10.89C9.84 10.78 10 10.6 10.1 10.45C10.23 10.31 10.27 10.2 10.35 10.04C10.43 9.87 10.39 9.73 10.33 9.61C10.27 9.5 9.77 8.26 9.56 7.77C9.36 7.29 9.16 7.35 9 7.34C8.86 7.34 8.7 7.33 8.53 7.33Z" />
    </svg>
    <svg class="close-icon" viewBox="0 0 512 512">
      <path d="M278.6 256l68.2-68.2c6.2-6.2 6.2-16.4 0-22.6-6.2-6.2-16.4-6.2-22.6 0L256 233.4l-68.2-68.2c-6.2-6.2-16.4-6.2-22.6 0-3.1 3.1-4.7 7.2-4.7 11.3 0 4.1 1.6 8.2 4.7 11.3l68.2 68.2-68.2 68.2c-3.1 3.1-4.7 7.2-4.7 11.3 0 4.1 1.6 8.2 4.7 11.3 6.2 6.2 16.4 6.2 22.6 0l68.2-68.2 68.2 68.2c6.2 6.2 16.4 6.2 22.6 0 6.2-6.2 6.2-16.4 0-22.6L278.6 256z" />
    </svg>
  </label>
</div>

<div class="sticky-chat">
  <div class="chat-content">
    <div class="chat-header">
      <svg viewBox="0 0 32 32">
        <path d="M24,22a1,1,0,0,1-.64-.23L18.84,18H17A8,8,0,0,1,17,2h6a8,8,0,0,1,2,15.74V21a1,1,0,0,1-.58.91A1,1,0,0,1,24,22ZM17,4a6,6,0,0,0,0,12h2.2a1,1,0,0,1,.64.23L23,18.86V16.92a1,1,0,0,1,.86-1A6,6,0,0,0,23,4Z" />
        <rect height="2" width="2" x="19" y="9"></rect>
        <rect height="2" width="2" x="14" y="9"></rect>
        <rect height="2" width="2" x="24" y="9"></rect>
        <path d="M8,30a1,1,0,0,1-.42-.09A1,1,0,0,1,7,29V25.74a8,8,0,0,1-1.28-15,1,1,0,1,1,.82,1.82,6,6,0,0,0,1.6,11.4,1,1,0,0,1,.86,1v1.94l3.16-2.63A1,1,0,0,1,12.8,24H15a5.94,5.94,0,0,0,4.29-1.82,1,1,0,0,1,1.44,1.4A8,8,0,0,1,15,26H13.16L8.64,29.77A1,1,0,0,1,8,30Z" />
      </svg>
      <div class="title">מוזמן לכתוב לנו בכל עת <span>מנהל יצור איתך קשר</span>
      </div>
    </div>
    <div class="chat-text"><span>היי איך ניתן לעזור לך היום?</span>
      <span class="typing">
        <svg viewBox="0 0 512 512">
          <circle cx="256" cy="256" r="48"></circle>
          <circle cx="416" cy="256" r="48"></circle>
          <circle cx="96" cy="256" r="48"></circle>
        </svg>
      </span>
    </div>
  </div>
  <a class="chat-button" href="https://api.whatsapp.com/send?phone=972544871731" rel="nofollow noreferrer" target="_blank">
    <span>Type a message</span>
    <svg viewBox="0 0 32 32">
      <path d="M19.47,31a2,2,0,0,1-1.8-1.09l-4-7.57a1,1,0,0,1,1.77-.93l4,7.57L29,3.06,3,12.49l9.8,5.26,8.32-8.32a1,1,0,0,1,1.42,1.42l-8.85,8.84a1,1,0,0,1-1.17.18L2.09,14.33a2,2,0,0,1,.25-3.72L28.25,1.13a2,2,0,0,1,2.62,2.62L21.39,29.66A2,2,0,0,1,19.61,31Z" />
    </svg>
  </a>
</div>
    <!-- chat -->

    <!-- Scripts -->

    <!-- jQuery Plugin -->
    <script src="assets/js/jquery-3.2.0.min.js"></script>
    <script src="assets/js/jquery-ui.js"></script>

    <!-- Owl Carousel Plugin -->
    <script src="assets/js/owl.carousel.min.js"></script>
    <!-- Main Counterup Plugin-->
    <script src="assets/js/jquery.counterup.min.js"></script>
    <script src="assets/js/countdown.js"></script>
    <script src="assets/js/jquery.meanmenu.js"></script>
    <script src="assets/js/jquery.scrollUp.js"></script>
    <script src="assets/js/jquery.mixitup.min.js"></script>
    <script src="assets/js/jquery.waypoints.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="assets/js/bootstrap.min.js"></script>
    <!-- Main Script -->
    <script src="assets/js/theme.js"></script>
    <script src="/script.js"></script>
       <script src="/script.js"></script>
    <script src="/scriptblog.js"></script>
        <link rel="stylesheet" href="styleblog.css" />

<script src="https://cdn.enable.co.il/licenses/enable-L21234i1gm0fzs6d-0723-57762/init.js"></script>
        <link rel="stylesheet" href="stylecss.css" />

  </body>
</html>
    """
    save_to_html(html_content, html_file_path)
    print(f"HTML file '{html_link}' created with blog content.")

    db_config = {
       "host": "local host",
        "user": "username",
        "password": "password",
        "database": "Db"
    }

    save_to_db(blog_content, prompt, db_config, html_link)
    print("Blog content and HTML link added to the database.")

if __name__ == "__main__":
    main()
